name: moor_shared
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Dart
  cupertino_icons: ^0.1.0
  moor: ^3.1.0
  rxdart: ^0.24.0
  intl: ^0.16.0

  # Database for mobile and Desktop
  moor_ffi: ^0.6.0
  
  # Helper to find the database path on mobile
  path_provider: ^1.6.0
  path: ^1.7.0

  # Web

dev_dependencies:
  moor_generator: ^3.1.0
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
